export type RiskLevel = "Critical" | "High" | "Medium" | "Low";

export interface Question {
  id: number;
  text: string;
  textBn: string;
  theme: string;
  riskLevel: RiskLevel;
  weight: number;
  isShortAnswer?: boolean;
}

export const QUESTIONS: Question[] = [
  {
    id: 1,
    text: "Do all workers have written appointment letters or employment documents in their personnel files?",
    textBn: "সকল কর্মীর ব্যক্তিগত ফাইলে কি লিখিত নিয়োগপত্র বা কর্মসংস্থান দলিল আছে?",
    theme: "Employment documentation",
    riskLevel: "Critical",
    weight: 8,
  },
  {
    id: 2,
    text: "Are worker age documents checked and stored before recruitment?",
    textBn: "নিয়োগের আগে কি কর্মীর বয়সের দলিল যাচাই ও সংরক্ষণ করা হয়?",
    theme: "Child labour prevention",
    riskLevel: "Critical",
    weight: 8,
  },
  {
    id: 3,
    text: "Does the factory keep an updated worker register?",
    textBn: "কারখানায় কি একটি হালনাগাদ কর্মী রেজিস্টার রাখা হয়?",
    theme: "Worker register",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 4,
    text: "Are daily attendance records complete and matched with wage records?",
    textBn: "দৈনিক হাজিরা রেকর্ড কি সম্পূর্ণ এবং মজুরি রেকর্ডের সাথে মিলানো?",
    theme: "Attendance and wage linkage",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 5,
    text: "Are normal working hours and overtime hours documented separately?",
    textBn: "সাধারণ কর্মঘণ্টা এবং ওভারটাইম ঘণ্টা কি আলাদাভাবে নথিভুক্ত?",
    theme: "Working hours documentation",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 6,
    text: "Is overtime voluntary and approved through a documented process?",
    textBn: "ওভারটাইম কি স্বেচ্ছামূলক এবং একটি নথিভুক্ত প্রক্রিয়ার মাধ্যমে অনুমোদিত?",
    theme: "Overtime control",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 7,
    text: "Are weekly holidays and rest days recorded and traceable?",
    textBn: "সাপ্তাহিক ছুটি ও বিশ্রামের দিন কি নথিভুক্ত এবং অনুসরণযোগ্য?",
    theme: "Rest day compliance",
    riskLevel: "Medium",
    weight: 3,
  },
  {
    id: 8,
    text: "Are wage slips or wage records provided and retained?",
    textBn: "মজুরি স্লিপ বা মজুরি রেকর্ড কি প্রদান ও সংরক্ষণ করা হয়?",
    theme: "Wage documentation",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 9,
    text: "Are minimum wage, grade, overtime rate, and deductions clearly shown in payroll records?",
    textBn: "নূন্যতম মজুরি, গ্রেড, ওভারটাইম হার এবং কর্তন কি বেতন রেকর্ডে স্পষ্টভাবে দেখানো?",
    theme: "Wage calculation",
    riskLevel: "Critical",
    weight: 8,
  },
  {
    id: 10,
    text: "Are all deductions from wages documented and explained to workers?",
    textBn: "মজুরি থেকে সকল কর্তন কি নথিভুক্ত এবং কর্মীদের কাছে ব্যাখ্যা করা হয়?",
    theme: "Wage deduction control",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 11,
    text: "Does the factory maintain leave records for annual, casual, sick, festival, and maternity leave?",
    textBn: "কারখানায় কি বার্ষিক, নৈমিত্তিক, অসুস্থতা, উৎসব ও মাতৃত্বকালীন ছুটির রেকর্ড রাখা হয়?",
    theme: "Leave management",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 12,
    text: "Are maternity protection records and benefits documented?",
    textBn: "মাতৃত্ব সুরক্ষা রেকর্ড ও সুবিধা কি নথিভুক্ত?",
    theme: "Maternity protection",
    riskLevel: "Critical",
    weight: 8,
  },
  {
    id: 13,
    text: "Is there a written grievance procedure workers can use without retaliation?",
    textBn: "কর্মীরা কি প্রতিশোধের ভয় ছাড়াই ব্যবহার করতে পারেন এমন একটি লিখিত অভিযোগ পদ্ধতি আছে?",
    theme: "Grievance system",
    riskLevel: "Critical",
    weight: 8,
  },
  {
    id: 14,
    text: "Are grievance records reviewed and closed with corrective actions?",
    textBn: "অভিযোগ রেকর্ড কি পর্যালোচনা করা হয় এবং সংশোধনমূলক পদক্ষেপ সহ বন্ধ করা হয়?",
    theme: "Grievance closure",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 15,
    text: "Does the factory have an anti-harassment policy communicated to workers?",
    textBn: "কারখানায় কি কর্মীদের জানানো একটি হয়রানি-বিরোধী নীতি আছে?",
    theme: "Harassment prevention",
    riskLevel: "Critical",
    weight: 8,
  },
  {
    id: 16,
    text: "Is there a process for receiving, investigating, and resolving harassment complaints?",
    textBn: "হয়রানির অভিযোগ গ্রহণ, তদন্ত ও সমাধানের কি কোনো প্রক্রিয়া আছে?",
    theme: "Harassment response",
    riskLevel: "Critical",
    weight: 8,
  },
  {
    id: 17,
    text: "Is a participation committee or worker-management communication mechanism documented?",
    textBn: "কোনো অংশগ্রহণ কমিটি বা কর্মী-ব্যবস্থাপনা যোগাযোগ পদ্ধতি কি নথিভুক্ত?",
    theme: "Worker participation",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 18,
    text: "Are participation committee meetings documented regularly?",
    textBn: "অংশগ্রহণ কমিটির সভা কি নিয়মিত নথিভুক্ত হয়?",
    theme: "Worker communication",
    riskLevel: "Medium",
    weight: 3,
  },
  {
    id: 19,
    text: "Are trade union or worker association rights addressed in policy and worker communication?",
    textBn: "ট্রেড ইউনিয়ন বা কর্মী সংস্থার অধিকার কি নীতি ও কর্মী যোগাযোগে বলা আছে?",
    theme: "Freedom of association",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 20,
    text: "Does the factory maintain labour-compliance training records?",
    textBn: "কারখানায় কি শ্রম-সম্মতি প্রশিক্ষণ রেকর্ড রাখা হয়?",
    theme: "Training records",
    riskLevel: "Medium",
    weight: 3,
  },
  {
    id: 21,
    text: "Are disciplinary actions documented with clear process and worker acknowledgement?",
    textBn: "শাস্তিমূলক পদক্ষেপ কি স্পষ্ট প্রক্রিয়া ও কর্মীর স্বীকৃতি সহ নথিভুক্ত?",
    theme: "Disciplinary procedure",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 22,
    text: "Are termination, resignation, and final settlement records complete?",
    textBn: "ছাঁটাই, পদত্যাগ ও চূড়ান্ত নিষ্পত্তির রেকর্ড কি সম্পূর্ণ?",
    theme: "Separation and settlement",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 23,
    text: "Are provident fund or benefit records maintained where applicable?",
    textBn: "প্রযোজ্য ক্ষেত্রে কি ভবিষ্য তহবিল বা সুবিধার রেকর্ড রাখা হয়?",
    theme: "Benefits and provident fund",
    riskLevel: "Medium",
    weight: 3,
  },
  {
    id: 24,
    text: "Are previous audit findings or CAP items tracked to closure?",
    textBn: "পূর্ববর্তী অডিট ফলাফল বা CAP আইটেম কি বন্ধ পর্যন্ত অনুসরণ করা হয়?",
    theme: "CAP management",
    riskLevel: "High",
    weight: 5,
  },
  {
    id: 25,
    text: "What are the top three compliance documents the factory cannot produce within 24 hours?",
    textBn: "আপনার কারখানা ২৪ ঘণ্টার মধ্যে কোন তিনটি কমপ্লায়েন্স ডকুমেন্ট দেখাতে পারবে না?",
    theme: "Audit readiness",
    riskLevel: "Critical",
    weight: 8,
    isShortAnswer: true,
  },
];

export const MAX_RISK_SCORE = 141;
